from programs.views.residentials_views.child_views import *
from programs.views.residentials_views.caretaker_views import *
from programs.views.residentials_views.health_record_views import *
from programs.views.residentials_views.residential_finance_views import *
from programs.views.ifashe_views.family_views import *
from programs.views.ifashe_views.child_views import *
from programs.views.ifashe_views.parent_views import *
from programs.views.ifashe_views.sponsorship_views import *
from programs.views.ifashe_views.school_views import *
from programs.views.internships_views import *
